/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DayComponentMax: typeof import('./src/components/DayComponentMax.vue')['default']
    DayComponentMin: typeof import('./src/components/DayComponentMin.vue')['default']
    DayGantt: typeof import('./src/components/DayGantt.vue')['default']
    DayGanttBar: typeof import('./src/components/DayGanttBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}
